## Import Libraries

In [1]:
import numpy as np
import pandas as pd
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
from sklearn.metrics.pairwise import cosine_similarity # This is the algorithm we use to build our recommendations 

In [3]:
#reading in the data
shades = pd.read_csv('Data/allshades_updated.csv')

In [4]:
shades.head()

Foundation  \
0  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
1  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
2  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
3  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
4  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   

                                                 url      shade  \
0  https://www.ulta.com/ultimate-coverage-24-hour...      Shell   
1  https://www.ulta.com/ultimate-coverage-24-hour...      Linen   
2  https://www.ulta.com/ultimate-coverage-24-hour...  Alabaster   
3  https://www.ulta.com/ultimate-coverage-24-hour...  Porcelain   
4  https://www.ulta.com/ultimate-coverage-24-hour...      Ivory   

               hex        hue       sat  lightness  red  green  blue  
0  (239, 203, 164)  31.200000  0.700935   0.790196  239    203   164  
1  (243, 206, 176)  26.865672  0.736264   0.821569  243    206   176  
2  (242, 203, 180)  22.258065  0.704545   0.827451  242    203   180  
3  (246, 200, 167)  25.063291  0.814433   0.809804  246    200   167  
4  (240, 196, 171)  21.739130  0.696970   0.805882  240    196   171

In [5]:
shades.tail()

Foundation  \
3039  SEPHORA COLLECTION Best Skin Ever Liquid Found...   
3040  SEPHORA COLLECTION Best Skin Ever Liquid Found...   
3041  SEPHORA COLLECTION Best Skin Ever Liquid Found...   
3042  Lancôme Bienfait Teinté Beauty Balm Sunscreen ...   
3043  bareMinerals bareSkin® Pure Brightening Serum ...   

                                                    url       shade  \
3039  https://www.sephora.com/product/sephora-collec...           N   
3040  https://www.sephora.com/product/sephora-collec...           P   
3041  https://www.sephora.com/product/sephora-collec...           N   
3042  https://www.sephora.com/product/bienfait-teint...        Sand   
3043  https://www.sephora.com/product/bareskin-pure-...  Bare Mocha   

                  hex        hue       sat  lightness  red  green  blue  
3039   (134, 102, 69)  30.461538  0.320197   0.398039  134    102    69  
3040    (123, 87, 57)  27.272727  0.366667   0.352941  123     87    57  
3041    (122, 90, 60)  29.032258  0.340659   0.356863  122     90    60  
3042  (210, 159, 119)  26.373626  0.502762   0.645098  210    159   119  
3043   (175, 115, 87)  19.090909  0.354839   0.513725  175    115    87

In [24]:
my_skin = [[80,48,33]]
foundation = [[108, 57, 35]]

In [27]:
shades

Foundation  \
0     BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
1     BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
2     BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
3     BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
4     BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
5     BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
6     BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
7     BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
8     BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
9     BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
10    BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
11    BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
12    BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
13    BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
14    BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
15    BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
16    BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
17    BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
18    BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
19    BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
20    BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
21    BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
22    BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
23    BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
24    BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
25    BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
26    BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
27    BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
28    BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
29    BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
30    BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
31    BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
32    BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
33    BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
34    BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
35    BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
36    BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
37    BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
38    BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
39    BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
40    BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
41    BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
42    Benefit Cosmetics Hello Happy Flawless Brighte...   
43    Benefit Cosmetics Hello Happy Flawless Brighte...   
44    Benefit Cosmetics Hello Happy Flawless Brighte...   
45    Benefit Cosmetics Hello Happy Flawless Brighte...   
46    Benefit Cosmetics Hello Happy Flawless Brighte...   
47    Benefit Cosmetics Hello Happy Flawless Brighte...   
48    Benefit Cosmetics Hello Happy Flawless Brighte...   
49    Benefit Cosmetics Hello Happy Flawless Brighte...   
50    Benefit Cosmetics Hello Happy Flawless Brighte...   
51    Benefit Cosmetics Hello Happy Flawless Brighte...   
52    Benefit Cosmetics Hello Happy Flawless Brighte...   
53    Benefit Cosmetics Hello Happy Flawless Brighte...   
54    Benefit Cosmetics Hello Happy Velvet Powder Fo...   
55    Benefit Cosmetics Hello Happy Velvet Powder Fo...   
56    Benefit Cosmetics Hello Happy Velvet Powder Fo...   
57    Benefit Cosmetics Hello Happy Velvet Powder Fo...   
58    Benefit Cosmetics Hello Happy Velvet Powder Fo...   
59    Benefit Cosmetics Hello Happy Velvet Powder Fo...   
60    Benefit Cosmetics Hello Happy Velvet Powder Fo...   
61    Benefit Cosmetics Hello Happy Velvet Powder Fo...   
62    Benefit Cosmetics Hello Happy Velvet Powder Fo...   
63    Benefit Cosmetics Hello Happy Velvet Powder Fo...   
64    Benefit Cosmetics Hello Happy Velvet Powder Fo...   
65    Benefit Cosmetics Hello Happy Velvet Powder Fo...   
66    It Cosmetics Your Skin But Better Foundation +...   
67    It Cosmetics Your Skin But 

In [25]:
cosine_similarity(my_skin, foundation)

array([[0.99678845]])

In [31]:
# my actual foundation 
shades.iloc[2698]
actual_foundation = [[129, 86, 51]]

In [33]:
cosine_similarity(my_skin, actual_foundation, dense_output=False)

array([[0.99874037]])

In [34]:
shades.head()

Foundation  \
0  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
1  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
2  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
3  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
4  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   

                                                 url      shade  \
0  https://www.ulta.com/ultimate-coverage-24-hour...      Shell   
1  https://www.ulta.com/ultimate-coverage-24-hour...      Linen   
2  https://www.ulta.com/ultimate-coverage-24-hour...  Alabaster   
3  https://www.ulta.com/ultimate-coverage-24-hour...  Porcelain   
4  https://www.ulta.com/ultimate-coverage-24-hour...      Ivory   

               hex        hue       sat  lightness  red  green  blue  
0  (239, 203, 164)  31.200000  0.700935   0.790196  239    203   164  
1  (243, 206, 176)  26.865672  0.736264   0.821569  243    206   176  
2  (242, 203, 180)  22.258065  0.704545   0.827451  242    203   180  
3  (246, 200, 167)  25.063291  0.814433   0.809804  246    200   167  
4  (240, 196, 171)  21.739130  0.696970   0.805882  240    196   171

In [39]:
shades_new = shades[['Foundation','red', 'green', 'blue']].copy()

In [40]:
shades_new.head()

Foundation  red  green  blue
0  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...  239    203   164
1  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...  243    206   176
2  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...  242    203   180
3  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...  246    200   167
4  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...  240    196   171

In [47]:
shades_new.head()

Foundation  red  green  blue
0  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...  239    203   164
1  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...  243    206   176
2  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...  242    203   180
3  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...  246    200   167
4  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...  240    196   171

In [52]:
my_shade = {'Foundation': 'My Shade' , 'red':80 , 'green':48 ,'blue':33}

In [81]:
cosine_similarity([[239, 203, 164]], [[80, 48, 33]])

array([[0.97877981]])

In [82]:
cosine_similarity([[240, 196, 171]], [[80, 48, 33]])

array([[0.97794488]])

In [91]:
# function to apply to dataframe to compare cosine similarities to myshade

def foundation(row):
    red = row['red']
    green = row['green']
    blue = row['blue']
    foundation_shade = [[red, green, blue]]
    my_shade = [[80, 48, 33]]
    similar = cosine_similarity(my_shade, foundation_shade)
    similar = similar[0][0]
    return similar

In [93]:
shades_new['similarities'] = shades_new.apply(foundation, axis=1)

In [98]:
shades_new.sort_values(by='similarities', ascending=False).head(3)

red  green  blue  \
Foundation                                                             
KVD Vegan Beauty Lock-It Powder Foundation Refi...  163     98    68   
Estée Lauder Double Wear Light Soft Matte Hydra...  132     79    55   
Tarte Face Tape Foundation 53H                      180    109    75   

                                                    similarities  
Foundation                                                        
KVD Vegan Beauty Lock-It Powder Foundation Refi...      0.999994  
Estée Lauder Double Wear Light Soft Matte Hydra...      0.999994  
Tarte Face Tape Foundation 53H                          0.999990

In [ ]:
# This returns us the top 3 most similar foundations, now we will search the link to compare. 