## Import Libraries

In [1]:
import numpy as np
import pandas as pd
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
from sklearn.metrics.pairwise import cosine_similarity # This is the algorithm we will use to build our recommendations 

# Reading in the Updated Data

In [2]:
#reading in the data
shades = pd.read_csv('Data/allshades_updated.csv')

In [3]:
# Viewing the first 5 rows
shades.head()

Foundation  \
0  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
1  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
2  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
3  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
4  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   

                                                 url      shade  \
0  https://www.ulta.com/ultimate-coverage-24-hour...      Shell   
1  https://www.ulta.com/ultimate-coverage-24-hour...      Linen   
2  https://www.ulta.com/ultimate-coverage-24-hour...  Alabaster   
3  https://www.ulta.com/ultimate-coverage-24-hour...  Porcelain   
4  https://www.ulta.com/ultimate-coverage-24-hour...      Ivory   

               hex        hue       sat  lightness  red  green  blue  
0  (239, 203, 164)  31.200000  0.700935   0.790196  239    203   164  
1  (243, 206, 176)  26.865672  0.736264   0.821569  243    206   176  
2  (242, 203, 180)  22.258065  0.704545   0.827451  242    203   180  
3  (246, 200, 167)  25.063291  0.814433   0.809804  246    200   167  
4  (240, 196, 171)  21.739130  0.696970   0.805882  240    196   171

In [4]:
# Viewing the last 5 rows
shades.tail()

Foundation  \
3039  SEPHORA COLLECTION Best Skin Ever Liquid Found...   
3040  SEPHORA COLLECTION Best Skin Ever Liquid Found...   
3041  SEPHORA COLLECTION Best Skin Ever Liquid Found...   
3042  Lancôme Bienfait Teinté Beauty Balm Sunscreen ...   
3043  bareMinerals bareSkin® Pure Brightening Serum ...   

                                                    url       shade  \
3039  https://www.sephora.com/product/sephora-collec...           N   
3040  https://www.sephora.com/product/sephora-collec...           P   
3041  https://www.sephora.com/product/sephora-collec...           N   
3042  https://www.sephora.com/product/bienfait-teint...        Sand   
3043  https://www.sephora.com/product/bareskin-pure-...  Bare Mocha   

                  hex        hue       sat  lightness  red  green  blue  
3039   (134, 102, 69)  30.461538  0.320197   0.398039  134    102    69  
3040    (123, 87, 57)  27.272727  0.366667   0.352941  123     87    57  
3041    (122, 90, 60)  29.032258  0.340659   0.356863  122     90    60  
3042  (210, 159, 119)  26.373626  0.502762   0.645098  210    159   119  
3043   (175, 115, 87)  19.090909  0.354839   0.513725  175    115    87

In [21]:
#shades

# Lets test the Cosine Similarity Function

In [23]:
shades.iloc[2698] # This is my actual foundation 
actual_foundation = [[129, 86, 51]] # This is the RGB values for my foundation
my_skin = [[80, 53, 39]] # This is the RGB values from our extract dominant color algorithm for my photo 

In [24]:
cosine_similarity(my_skin, actual_foundation, dense_output=False) # Calculating the cosine similarity of my skin and my actual foundation

array([[0.99767061]])

In [34]:
shades.head()

Foundation  \
0  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
1  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
2  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
3  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   
4  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...   

                                                 url      shade  \
0  https://www.ulta.com/ultimate-coverage-24-hour...      Shell   
1  https://www.ulta.com/ultimate-coverage-24-hour...      Linen   
2  https://www.ulta.com/ultimate-coverage-24-hour...  Alabaster   
3  https://www.ulta.com/ultimate-coverage-24-hour...  Porcelain   
4  https://www.ulta.com/ultimate-coverage-24-hour...      Ivory   

               hex        hue       sat  lightness  red  green  blue  
0  (239, 203, 164)  31.200000  0.700935   0.790196  239    203   164  
1  (243, 206, 176)  26.865672  0.736264   0.821569  243    206   176  
2  (242, 203, 180)  22.258065  0.704545   0.827451  242    203   180  
3  (246, 200, 167)  25.063291  0.814433   0.809804  246    200   167  
4  (240, 196, 171)  21.739130  0.696970   0.805882  240    196   171

## Creating a new Data Frame based on just the RGB values and the foundation column

In [39]:

shades_new = shades[['Foundation','red', 'green', 'blue']].copy()

In [40]:
shades_new.head()

Foundation  red  green  blue
0  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...  239    203   164
1  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...  243    206   176
2  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...  242    203   180
3  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...  246    200   167
4  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...  240    196   171

In [47]:
shades_new.head()

Foundation  red  green  blue
0  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...  239    203   164
1  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...  243    206   176
2  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...  242    203   180
3  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...  246    200   167
4  BECCA Cosmetics Ultimate Coverage 24 Hour Foun...  240    196   171

### Testing Cosine Similarities between various foundations and my shade

In [52]:
my_shade = {'Foundation': 'My Shade' , 'red':80 , 'green':48 ,'blue':33}

In [81]:
cosine_similarity([[239, 203, 164]], [[80, 48, 33]])

array([[0.97877981]])

In [82]:
cosine_similarity([[240, 196, 171]], [[80, 48, 33]])

array([[0.97794488]])

# Creating our Recommender System

In [91]:
# function to apply to dataframe to compare cosine similarities to myshade

def foundation(row): # accepts a row of the dataframe to use it on the shades_new df
    red = row['red'] # the value red is equal to the rows value
    green = row['green'] # the value green is equal to the rows value
    blue = row['blue'] # the value blue is equal to the rows value
    foundation_shade = [[red, green, blue]]
    my_shade = [[80, 48, 33]] #plugging in the skin foundation found from the algorithm 
    similar = cosine_similarity(my_shade, foundation_shade) # calculating the cosine similarity 
    similar = similar[0][0]
    return similar

In [93]:
# adding a new column to the dataframe to store each cosine similarities from the image extracted value to the dataset
shades_new['similarities'] = shades_new.apply(foundation, axis=1)

In [112]:
shades_new.sort_values(by='similarities', ascending=False).head(1) # Finding the closest matched foundation

red  green  blue  \
Foundation                                                             
KVD Vegan Beauty Lock-It Powder Foundation Refi...  163     98    68   

                                                    similarities  
Foundation                                                        
KVD Vegan Beauty Lock-It Powder Foundation Refi...      0.999994

A similarity of .999 is very high and a great start to a recommendation. 

# Conclusions and Next Steps

In conlcusion our algorithm is able to extract the image and determine the skin color, our next steps include building out the application in Flask. 